apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rekor-cli
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rekor-cli
    app.kubernetes.io/part-of: rhtas-cli-1-0-beta
  name: rekor-cli
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rekor-cli
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rekor-cli
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rhtas-cli-1-0-beta/rekor-cli@sha256:45504a0076fa75e707c2628583c8aeb86ea1d16341294cb136f373bc39125128
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 15m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
