apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rekor-cli
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rekor-cli
    app.kubernetes.io/part-of: rhtas-cli-1-0-beta
  name: rekor-cli
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: rekor-cli
status:
  loadBalancer: {}
