apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cosign
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cosign
    app.kubernetes.io/part-of: rhtas-cli-1-0-beta
  name: cosignvbv4
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: cosign
    weight: 100
status: {}
