apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: gitsign
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rhtas-cli-1-0-beta/gitsign@sha256:62a3e34b0b918aaa60dc6a0647548ae89da3597121fcc4be8cb571fb89bbe278
        name: container-image
        resources: {}
status: {}
