apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rekor-cli
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rhtas-cli-1-0-beta/rekor-cli@sha256:ad16800d7d10bd98950aac8f5c472ac7fd6d1370b0259b8eb8ea50201054659f
        name: container-image
        resources: {}
status: {}
