apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gitsign
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitsign
    app.kubernetes.io/part-of: rhtas-cli-1-0-beta
  name: gitsign
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: gitsign
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: gitsign
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rhtas-cli-1-0-beta/gitsign@sha256:2581f2bf3cce4c20f65164083ef103319e06dc355275e8d9acfda371377bb9f5
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 15m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
