apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gitsign
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitsign
    app.kubernetes.io/part-of: rhtas-cli-1-0-beta
  name: gitsign
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: gitsign
status:
  loadBalancer: {}
